### ISSUE TITLE
Latter prefetch may evict previous prefetched embeddings

### ISSUE THREAD

**Issue by zhuzilin** [pytorch/FBGEMM#1201]
Our team is trying to utilize the `SplitTableBatchedEmbeddingBagsCodegen.prefetch` to accelerate training in torchrec. And during the survey, I found that the `lru_cache_insert_kernel` and `lfu_cache_insert_kernel` may evict the id prefetched last time. For example, in the following pipeline, if `prefetch_2`, which is prefetching the data for `compute_2`, may accidentally evict the data being used by `compute_1`.
```
stream 0              |    compute_0    |    compute_1    |    compute_2    | ...
stream 1 | prefetch_0 | prefetch_1 |    | prefetch_2 |    | prefetch_3 | ...
```
A quick fix for LRU is passing the first element of `self.timesteps_prefetched` as the eviction threshold in `lru_cache_insert` kernels. But I haven't figured out a good way to fix LFU kernels...

Also, a minor issue, the current `benchmark_pipelined_requests` doesn't seem to do pipelining of `prefetch` and `forward`, as they are using the same stream.

**Comment by colin2328** [comment]
cc @jianyuh @jspark1105

**Comment by jianyuh** [comment]
Thanks for reporting the issue! Feel free to submit a PR on fixing LRU and `benchmark_pipelined_requests` benchmark (https://github.com/pytorch/FBGEMM/blob/c1a63cb6b9e3f369619ecd53f7aadf1a6d9384f3/fbgemm_gpu/bench/bench_utils.py#L385 with multiple streams). For LFU, not sure if it is easy to create some unique tag for the frequency counter.

**Comment by zhuzilin** [comment]
@jianyuh 
> For LFU, not sure if it is easy to create some unique tag for the frequency counter.

I was also thinking about using maybe a bit as tag for "being used". However, it's hard to determine when could we untag them, as user may or may not run backward on the model...

> Feel free to submit a PR

I'll try for a PR :) (may be 2 separate ones for them)

**Comment by jasonjk-park** [comment]
SW cache is not thread-safe (or multi-stream safe in this case) - prefetching and computing at the same time is not the intention of the original design. Having some sort of lock/mutex would make it work, however, that'd prevent us to use in pipelined fashion as well.

It'd be better to support multi-stream safeness completely (not just LRU, but also LFU, and probably replacement policy agnostic way) rather than giving false impression that it works by partially allowing it.

**Comment by zhuzilin** [comment]
@jasonjk-park @jianyuh 
> It'd be better to support multi-stream safeness completely (not just LRU, but also LFU, and probably replacement policy agnostic way) rather than giving false impression that it works by partially allowing it.

Totally agree. And to have a general solution, we would probably need to introduce a state to record whether a cache line is being used. I believe the hard part is to make sure the prefetch will update right between the model compute iterations, which leads to:

> it's hard to determine when could we untag them, as user may or may not run backward on the model...

For LRU, we could use the python object `self.timesteps_prefetched`, in which GIL would help us do the locking. But I'm afraid,  for the general case, there is not a small enough invariant that we could update in python... I wonder if you could share your ideas on this problem? Thank you:)

**Comment by jasonjk-park** [comment]
@zhuzilin 

> Totally agree. And to have a general solution, we would probably need to introduce a state to record whether a cache line is being used. I believe the hard part is to make sure the prefetch will update right between the model compute iterations, which leads to:

I think the problem is coming from where you are trying to pipeline prefetch and compute using two different streams. That is, design intention was to perform them in the same stream, so that they are serialized. only way you can parallelize is to create two different TBEs, which will own separate caches, so they can run using different streams.

> For LRU, we could use the python object `self.timesteps_prefetched`, in which GIL would help us do the locking. But I'm afraid, for the general case, there is not a small enough invariant that we could update in python... I wonder if you could share your ideas on this problem? Thank you:)

problem with this idea is that, while functionally it's correct, it does not make sense in terms of performance, and could actually make things worse.
when prefetch_1 cannot evict ones being used by compute_0, that means, we are not putting enough stuff into cache for compute_1, so you are slowing down compute_1.

I think there are few ways to solve this issue:
(1) as I said above, use multiple TBEs, and run them in different streams to parallelize. you won't need to update fbgemm at all.
(2) logically partition cache, so that some partitions are used only for compute and some parts are only for updates, and switch those partitions as we go. this would be much more involved change in fbgemm, and needs to solve various problems like how do we logically partition, which ones to choose for compute/updates, etc.

**Comment by zhuzilin** [comment]
@jasonjk-park 
First, I need to apologize for the figure in the issue description... What we are trying to do is actually:
```pyhton
stream 0 | prefetch_0 |   compute_0   | prefetch_2 |   compute_2   | prefetch_4 |   compute_4   | ...
stream 1              | prefetch_1 |   compute_1   | prefetch_3 |   compute_3   | ....
```
I'm sorry for any confusion caused by the wrong figure.

And I now understand your design intention, which is a little different from our understanding of "prefetch". I'll close this issue and the relevant PR. Thank you for the clarification!
