### ISSUE TITLE
Per Channel Linear Quantization Gap with FBGEMM between Skylake and Cascade lake  X86_64 CPU 

### ISSUE THREAD

**Issue by liangan1** [pytorch/FBGEMM#125]
**Description:**
We use per channel quantization for linear weights and per tensor affine quantization for activation in Pytorch based on the FBGEMM int8 kernel.  But when we evaluate the modules, we get the different result  in  Skylake and Cascade lake  X86_64 CPU. 

 The Mean Squared Error (MSE) is used to measure the gap between the output of fp32 linear and quantized linear. In order to validate this issue, we fetch the  input(8x128x768), weights(768x768) and bias from CoLA task in Bert model and use these data in a UnitTest.  the results are as following:

MSE  Cascade lake :  259.8453
MSE  Sky lake:  195320.5625

The above results show that Sky lake  get obviously larger  gap than Cascade lake.  if you want to reproduce the above result you can get  the code from https://github.com/liangan1/pytorch/tree/prv_bert and use the UT   test/test_per_channel_linear.py

**Environment:**
gcc version 7.2.1 20170829 (Red Hat 7.2.1-1) (GCC)
CentOS Linux release 7.4.1708 (Core)
conda 4.6.11

**Comment by jgong5** [comment]
@jianyuh @dskhudia @Jianhui-Li

**Comment by liangan1** [comment]
@jianyuh  @hongzhen1 all the txt data file can be found in https://github.com/liangan1/pytorch/tree/prv_bert/test

**Comment by PenghuiCheng** [comment]
@jgong5 @jianyuh @hongzhen1 @dskhudia 
Hi，I tested reduce_range True/False on cascade lake platform clx-8280(with https://github.com/pytorch/pytorch/pull/25667) ,the gap of  the accuracy of resnet50 model is atattched,reduce_range = True will weaken accuracy. Reduce range implementation depends on Hardware and algorithm implementation, should implement it in fbgemm kernel instead of in frontend ?By the way, In mkldnn kernel ,there is no this issue.
[INT8_reduce_range_on_cascade.xlsx](https://github.com/pytorch/FBGEMM/files/3733025/INT8_reduce_range_on_cascade.xlsx)

**Comment by PenghuiCheng** [comment]
update the accrucy of reduce range True/False on skx8180 with https://github.com/pytorch/pytorch/pull/25667 .
[INT8_reduce_range.xlsx](https://github.com/pytorch/FBGEMM/files/3753534/INT8_reduce_range.xlsx)

**Comment by Jianhui-Li** [comment]
@dskhudia @jianyuh  How can we educate user not to use "reduce_range = True" on HW with VNNI support?  It is supposed to help avoid overflow on SKX and prior ISA without VNNI, but VNNI doesn't have the overflow issue and Penghui found out that removing it helps with the accuracy.

**Comment by jianyuh** [comment]
Thanks @Jianhui-Li @PenghuiCheng @liangan1 @hongzhen1 @jgong5 ! I think we should add the run time detection for the CPU type. The user shouldn't detect the CPU type and configure `reduce_range` manually. The question is whether this `reduce_range = True/False` flag in PyTorch should delegate to FBGEMM or not. Inside FBGEMM we use `cpuinfo` to check the CPU types.  cc @raghuramank100 @dzhulgakov

**Comment by dskhudia** [comment]
Quantization users need not bother about type of hardware. IMO we should set reduce_range to true/false by querying the backend library. If the backend library can use VNNI and has VNNI available, the library returns false otherwise true to set reduce_range.

**Comment by imaginary-person** [comment]
Another example of difference between outputs is `test_lstm` of `quantization.bc.test_backward_compatibility.TestSerialization` (which is run from `test_quantization.py` in PyTorch), and fails on `xlarge` instances in CI, which are Cascade Lake machines.

cc @supriyar @jerryzh168 @raghuramank100

![CASCADE LAKE DIFFERENCE](https://user-images.githubusercontent.com/76181208/122681819-cd657500-d1bb-11eb-8360-cd28a7714bdf.PNG)

**Comment by imaginary-person** [comment]
Hello @dskhudia, please confirm if you mean `reduce_range` should be removed from the PyTorch code, and if `FBGEMM` should make the decision as to whether or not to use `AVX512_VNNI` (depending upon availability). Thank you!

**Comment by dskhudia** [comment]
@imaginary-person,

I meant PyTorch should set reduce_range to true on non-VNNI machines and VNNI machines if the backend library (such as FBGEMM, OneDNN, XNNPACK etc.) doesn't use VNNI instructions otherwise set reduce_range to false. As for the test, I think the test should be changed so that it passes both on VNNI and non-VNNI machines.

**Comment by imaginary-person** [comment]
Thank you for the clarification, @dskhudia!
