### ISSUE TITLE
incorrect install of develop versions?

### ISSUE THREAD

**Issue by min-xu-ai** [pytorch/FBGEMM#1394]
when I run "python setup.py install develop", it seems that only small portion of the python code get installed. Trying to import fbgemm_gpu.split_embedding_configs would result in an error for me.

**Comment by min-xu-ai** [comment]
using "python setup.py install" is fine for me.

**Comment by jianyuh** [comment]
Thanks @min-xu-ai for reporting this issue! I guess `python setup.py install develop` will keep the python files in place (original source folder), while `python setup.py install` will install it in the right Python install path.

**Comment by q10** [comment]
Closing this ticket as a lot of changes have taken place since it was filed. Specifically, we now only support Python 3.8 - 3.11, CUDA 11.7-11.8, and PyTorch 2.0+. For comprehensive instructions on how to build and install FBGEMM_GPU, please refer to the [Build Instructions](https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/docs/BuildInstructions.md) and  [Installation Instructions](https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/docs/InstallationInstructions.md). Please feel free to file a new ticket if you run into further issues with FBGEMM_GPU installation.
