### ISSUE TITLE
Which branch is stable to build from source with CUDA 11.7?

### ISSUE THREAD

**Issue by moderato** [pytorch/FBGEMM#1699]
Hello, I'm trying to build FBGEMM_GPU from source with CUDA 11.7 and Pytorch (also built from source). However I wasn't able to make it, as each time it gave me different errors.

I have tried Pytorch 1.13.0 (7c98e70) and 1.13.1 (49444c3) and failed. The errors were mainly `AttributeError: '_OpNamespace' 'fbgemm' object has no attribute xxx` where xxx can be `jagged_2d_to_dense` or `bound_check_indices` or something else. It seems like the FBGEMM_GPU versions under these two Pytorch commits are both 0.1.1 so I don't know if it means FBGEMM_GPU is too old here.

I was wondering which branch is stable and recommended for building from source? Any help would be appreciated.

**Comment by sryap** [comment]
Hi @moderato, I'm sorry to hear that you have a problem with building FBGEMM.  Could you please try https://github.com/pytorch/FBGEMM/releases/tag/v0.4.1?  We tested this with PyTorch v2.0 and CUDA v11.7 (please see software requirements in the release note).  For older PyTorch, please checkout other releases in https://github.com/pytorch/FBGEMM/releases.

Hope this helps

**Comment by q10** [comment]
@moderato Thanks for reaching out to us.  The error signature you encountered usually means that the library was built incorrectly - likely the environment variable `NVML_LIB_PATH` was missing at the time of build.

As building FBGEMM_GPU can be a challenge, we have provided a fully unabridged and up-to-date build instructions, which can be found [here](https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/docs/BuildInstructions.md).  Please let us know if you encounter any further issues.

**Comment by q10** [comment]
@moderato I presume you are referring to CUDA 11.7, bc 10.7 is very old and thus unsupported...

Could you follow the steps in the [build instructions](https://github.com/pytorch/FBGEMM/blob/main/fbgemm_gpu/docs/BuildInstructions.md) and let me know how it goes?  The instructions are dense, so you may have accidentally missed an instruction step.

Also, could you let me know what is your OS setup or Docker image, so that we can see if the issue is reproducible there?  

One thing to note is that almost all the tools used to build fbgemm_gpu are set up in a containerized environment, in order to keep the builds reproducible.  You may also want to try building using the installation scripts we have built up for our CI jobs (see example job and its scripts usage [here](https://github.com/pytorch/FBGEMM/blob/main/.github/workflows/fbgemm_gpu_cuda_release.yml)), which come with comprehensive checks to make sure that the setup is correct prior to building.

**Comment by moderato** [comment]
> I presume you are referring to CUDA 11.7, bc 10.7 is very old and thus unsupported...

Yes that's a typo. Fixed now. Thanks for pointing that out.

I just managed to build FBGEMM from source following the build instructions you provided. Here are the details of my building environment for reference:

CUDA: 11.7
OS: Linux Ubuntu 22.04
Pytorch: 2.0 ([c263bd43](https://github.com/pytorch/pytorch/commit/c263bd43e8e8502d4726643bc6fd046f0130ac0e))
FBGEMM_GPU: ([v0.4.1](https://github.com/pytorch/FBGEMM/tree/v0.4.1))
Python: 3.9
TORCH_CUDA_ARCH_LIST: 7.0,8.0

Not so sure why `pip install fbgemm_gpu==0.4.1` failed with the error I mentioned above though. The command that succeeded is `python setup.py install -DTORCH_CUDA_ARCH_LIST="7.0;8.0" --nvml_lib_path /usr/local/cuda/targets/x86_64-linux/lib/stubs/libnvidia-ml.so`.

Thank you for your quick and detailed support in fixing my problem!
