### ISSUE TITLE
[Question] - Does FBGEMM plan to support FP32 execution for GEMM kernel, and with int8 exeuction what all formats do we support other than u8s8u8?

### ISSUE THREAD

**Issue by naruto-raj** [pytorch/FBGEMM#1867]
With respect to FP16 we have kernels but do we have similar ones for BF16 or do we plan to support the same?

do we have support for embedding bag (FP32,bf16,int8 and different data type for int8) if not do we plan to add support?

**Comment by jspark1105** [comment]
No bf16 support since 1) FBGEMM for CPU main focus is for inference and 2) bf16 is added after we were actively adding new features to FBGEMM for CPU.

Functions in https://github.com/pytorch/FBGEMM/blob/main/include/fbgemm/FbgemmEmbedding.h are supporting embedding bag. See an example of how PyTorch embedding bag uses these at https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/EmbeddingBag.cpp#L241
Note we don't support bf16 for embedding bag as well.

**Comment by naruto-raj** [comment]
Thanks for your update @jspark1105. I have few follow up questions:
1) Does FBGEMM plan to support FP32 execution for GEMM kernel, and with int8 execution what formats do we support other than u8s8u8?
2)Does embedding bag have support for FP32,Fp16 & Int8?

**Comment by naruto-raj** [comment]
Thanks @sryap 

> Did you mean int8 inputs/outputs and FP32 accumulation? If not, could you please clarify

I would like to know if there's support for FP32 inputs/outputs for GEMM kernels in FBGEMM, if not do we plan to support the same.

**Comment by jspark1105** [comment]
> I would like to know if there's support for FP32 inputs/outputs for GEMM kernels in FBGEMM, if not do we plan to support the same
No since vendor libraries like Intel MKL already have good support with high performance for this.

> with int8 execution what formats do we support other than u8s8u8?
u8s8 input is the only format supported by x86 vector instructions hence the same in FBGEMM. Note that output can be s32 if you don't do requantization for the output.
