### ISSUE TITLE
[Question] Does AVX2 BlockingFactors work on a AVX512 machine for the int8 GEMM?

### ISSUE THREAD

**Issue by ykim362** [pytorch/FBGEMM#255]
Assuming I pack A, B matrix with AVX2 parameters (https://github.com/pytorch/FBGEMM/blob/ef5c9efe120d1e8b5b263ebe37be8cb0c9583cc2/include/fbgemm/Fbgemm.h#L413, https://github.com/pytorch/FBGEMM/blob/ef5c9efe120d1e8b5b263ebe37be8cb0c9583cc2/include/fbgemm/Fbgemm.h#L331), can this packed A, B used on AVX512 machine?

I am also using AVX2 parameter for the gemm function.
(https://github.com/pytorch/FBGEMM/blob/ef5c9efe120d1e8b5b263ebe37be8cb0c9583cc2/include/fbgemm/Fbgemm.h#L1358).

Thanks.

**Comment by dskhudia** [comment]
There are two conditions: 
1) They must be the same between packing and running, i.e., you may pack with avx2 blocking factors on an avx512 machine but while running with those packed matrices one must run with the same avx2 blocking factors.
2) Since blocking factors determine register blocking, they must be valid for the machine used., i.e., register usage doesn't exceed the available registers.  

I believe we have errors checks for these situations.

**Comment by ykim362** [comment]
Thanks for the clarification, @dskhudia !
I was having a trouble with this. I will double check my setting.

**Comment by ykim362** [comment]
@dskhudia 
I have a reproducer. It seems AVX2 blocking factors crashes on AVX512 machine. Could you confirm if this is expected?

https://github.com/marian-nmt/FBGEMM/blob/youki/avx512-avx2/bench/PackedFloatInOutBenchmark.cc#L98

https://github.com/marian-nmt/FBGEMM/blob/youki/avx512-avx2/bench/PackedFloatInOutBenchmark.cc#L224

https://github.com/marian-nmt/FBGEMM/blob/youki/avx512-avx2/bench/PackedFloatInOutBenchmark.cc#L227

https://github.com/marian-nmt/FBGEMM/blob/youki/avx512-avx2/bench/PackedFloatInOutBenchmark.cc#L271

**Comment by dskhudia** [comment]
@ykim362,

I am sorry for the late reply. I was off work. Please see isValidBlockingFactor function (https://github.com/pytorch/FBGEMM/blob/master/bench/GEMMsTunableBenchmark.cc#L314 ). Certain blocking factors have avx2/avx512 dependent constraints.
