### ISSUE TITLE
cannot import when using torch<2.5 on  arm cpu

### ISSUE THREAD

**Issue by Lix1993** [pytorch/FBGEMM#3275]
when using torch 2.5, I can import fbgemm_gpu , install command:
```
pip3 install torch==2.5 fbgemm_gpu  --index-url https://download.pytorch.org/whl/cpu
```

when torch<2.5, it fails
```
site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'
```

**Comment by q10** [comment]
Hi @Lix1993  With the latest fbgemm_gpu, there is a requirement to use torch 2.5.  If you would like to use torch 2.4, you will have to use a lower version of fbgemm_gpu:

```
pip3 install torch==2.5 fbgemm_gpu=0.8.0  --index-url https://download.pytorch.org/whl/cpu
```

**Comment by Lix1993** [comment]
thx
,I can use fbgemm_gpu==0.5.0 with torch 2.1 installed by pip,
but when I use torch build by myself, it failed.



Should I build torch with `USE_FBGEMM=ON`?

**Comment by q10** [comment]
Hi @Lix1993 if you are referring to building the torch library, we will defer you to the PyTorch team for the question since we are not the subject-matter experts.  However, a quick browse of the torch codebase suggests that `USE_FBGEMM=ON` should be used, since it will compile fbgemm kernels, some of which fbgemm_gpu uses.

**Comment by Lix1993** [comment]
Thx
