### ISSUE TITLE
quantized matrix multiplication question

### ISSUE THREAD

**Issue by jinz2014** [pytorch/FBGEMM#328]
Could you please point me to a quantized matrix-matrix multiplication example in the test or benchmark directory ?   That is to say,

C = A * B   // A, B, C are single-precision floating-point matrices 
C' = dequant (quant(A) * quant (B) )  // quant(A) and quant(B) are int8  matrices

Thanks

**Comment by dskhudia** [comment]
https://github.com/pytorch/FBGEMM/blob/master/bench/GEMMsBenchmark.cc#L190
The above computes C = A * B (A is uint8 and B is int8) and C is int32 result. You can convert C to float by multiplying (A_scale * B_scale/C_Scale) * ( C) + C_zero_point

A needs to be uint8 and B int8 due to the use of https://www.felixcloutier.com/x86/pmaddubsw instruction. If both of your matrices are int8, you can convert A matrix to be uint8 via a pre-processing step.

**Comment by jinz2014** [comment]
Are there examples in FBGEMM to show how A_scale, B_scale, C_Scale, and C_zero_point are computed ?   Could you please provide an example to show the entire process (from quantization to dequantization) ?

Thanks

**Comment by dskhudia** [comment]
A simple way of computing scale and zero point is using min and max values of a matrix.

For example, see the calculation of scale and zero point using min/max here: https://pytorch.org/docs/stable/quantization.html#observers

Once scale and zero points are calculated, using f = s ( q - z) 
(f is a floating point value, s is scale and z is zero point) each value in the matrix can be converted to a quantized value.    

For an example, see https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html .

You can pick a layer and print out the values.
