### ISSUE TITLE
Standalone sparse-dense matrix multiplication benchmark

### ISSUE THREAD

**Issue by marsupialtail** [pytorch/FBGEMM#390]
Hi, I am wondering if FBGEMM supports standalone sparse matrix dense matrix multiplication using the unrolling approach to get register blocking as mentioned in the new release notes. It seems like the test involves the operation fused with another matrix multiplication. I am wondering if an API similar to say MKL's SpMM exists for FBGEMM. Thank you!

**Comment by dskhudia** [comment]
@marsupialtail Such an API doesn't exist in FBGEMM at the moment.

**Comment by marsupialtail** [comment]
So is the easiest way of testing a SpMM fusing it with a quantized matmul at the moment?

**Comment by dskhudia** [comment]
@marsupialtail: Please take a look at the https://github.com/pytorch/FBGEMM/blob/master/bench/I8SpmdmBenchmark.cc

**Comment by marsupialtail** [comment]
So FBGEMM currently only supports int8 SpMM rn? Does it support fp32?

**Comment by dskhudia** [comment]
Currently it's int8 only.

**Comment by dskhudia** [comment]
fp32 and int8 dense-sparse exist at https://github.com/pytorch/FBGEMM/blob/master/bench/SparseDenseMMFP32Benchmark.cc and https://github.com/pytorch/FBGEMM/blob/master/bench/SparseDenseMMInt8Benchmark.cc

**Comment by CorbinFoucart** [comment]
Regarding the SparseDenseMMInt8Benchmark.cc example, it seems that both the input matrix and the output matrix must be transposed in order to use the API. Namely, if I have an input matrix A and am interested in the output matrix C, I must first transpose A to use the API and must transpose the output C^T as well to get C.

As these operations require memory copies which may be quite expensive, I've looked at using the CSC matrix format; for example the function `doSpmdmOnInpBuffer`. Is there a way to use this function, `doSpmdmOnInpBuffer`, standalone? Similar to the original poster, I've seen it only used in the context of an output pipeline.
