### ISSUE TITLE
Can there be a `FBGEMM_SPECIALIZED_QUANTIZE_AVX512` as well?

### ISSUE THREAD

**Issue by imaginary-person** [pytorch/FBGEMM#637]
Hello,

`FBGEMM_SPECIALIZED_QUANTIZE_AVX2` exists in `src/QuantUtils.cc`.
Does `FBGEMM_SPECIALIZED_QUANTIZE_AVX512` not currently exist because AVX512 didn't perform as well, when tested?

Thank you!

**Comment by dskhudia** [comment]
@imaginary-person,

Two reasons: 1) These operations are bandwidth bound and avx2 is enough to saturate the DRAM bandwidth. avx512 may benefit if the data is already in the caches and problems become compute bound. 2) For some cases, we only want to run avx2 instructions (to reduce frequency throttling) so having these other functions in avx2 helps. Also, we never got around to write avx512 version for some of these functions. Moreover, some Intel CPUs have only avx512 units and two avx2 units so moving to avx512 doesn't really help (and may hurt due to frequency throttling).

**Comment by imaginary-person** [comment]
Thank you for the helpful explanation!
