### ISSUE TITLE
use git submodules

### ISSUE THREAD

**Issue by t-vi** [pytorch/FBGEMM#87]
Would it be possible to use git submodules for ASMJIT?
The downloading during the (PyTorch) build can be a bit hard for me when hacking PyTorch while travelling.
Thanks!

**Comment by dskhudia** [comment]
I think so. For now, you can download asmjit once and point ASMJIT_SRC_DIR env var to the downloaded source code to avoid downloading with build. Particular git tag we use is in https://github.com/pytorch/FBGEMM/blob/master/cmake/modules/DownloadASMJIT.cmake

**Comment by dhpollack** [comment]
@t-vi I run into this problem all the time too.  I created a pull request.  Perhaps you could test it out and let me know if it works for you.

**Comment by dskhudia** [comment]
@dhpollack Thanks a lot for the pull request. Let me test its impact on Caffe2/Pytorch build.

**Comment by dskhudia** [comment]
Update: I had to revert the commit because adding submodules involves one more step so that internal tools work correctly. Will re-commit soon.

**Comment by dhpollack** [comment]
@dskhudia I also a few other things that I can update before you commit this pr.

1. I may want to use `${FBGEMM_SOURCE_DIR}` instead of `${CMAKE_SOURCE_DIR}`, because I'm not sure what the latter is when FBGEMM is a submodule itself.
2. You may want to consider renaming `${ASMJIT_SRC_DIR}` to `${ASMJIT_SOURCE_DIR}` to make it consistent with the other variables.

Let me know if you want me to make those changes.  I am not sure it matters as both work for me right now.

**Comment by dskhudia** [comment]
1) I will change it to FBGEMM_SOURCE_DIR
2) I remember it being having an issue with ASMJIT's cmake file. So we should keep that.

**Comment by dskhudia** [comment]
@t-vi and @dhpollack : It's fixed now. Once the pytorch's fbgemm submodule gets updated (should happen soon) to fbgemm's latest commit, pytorch build will not download asmjit at build time. 

@dhpollack : Thanks for your PR 👍
